namespace: purestorage
name: pure1
version: 0.0.1
readme: README.md
authors:
- Pure Storage Ansible Team (@sdodsley) <pure-ansible-team@purestorage.com>
description: Collection of modules to manage Pure Storage Pure1
license:
 - GPL-3.0-or-later
 - BSD-2-Clause
tags:
  - purestorage
  - pure1
  - storage
dependencies: {}
repository: https://github.com/Pure-Storage-Ansible/Pure1-Collection
documentation: https://github.com/Pure-Storage-Ansible/Pure1-Collection
issues: https://github.com/Pure-Storage-Ansible/Pure1-Collection/issues
