#!/usr/bin/python
# -*- coding: utf-8 -*-

# (c) 2021, Simon Dodsley (simon@everpuredata.com)
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
module: pure1_volumes
version_added: '1.3.0'
short_description: Collect volumes information from Pure1
description:
  - Collect volumes information from a Pure1 keyed on volume serial number.
options:
  array:
    description:
      - Filter to provide only volumes for a specifically named array
    type: str
author:
  - Everpure Ansible Team (@sdodsley) <pure-ansible-team@everpuredata.com>
extends_documentation_fragment:
  - everpure.pure1.everpure.p1
"""

EXAMPLES = r"""
- name: collect all volumes information
  everpure.pure1.pure1_volumes:
    register: pure1_volumes

- name: collect only volumes information for array X
  everpure.pure1.pure1_volumes:
    array: X
    register: pure1_volumes

- name: show volumes information
  debug:
    msg: "{{ pure1_info['pure1_volumes']['serial_numbers'] }}"

- name: show the Pure1 ID (NAID) of every volume
  debug:
    msg: "{{ item.value.name }} = {{ item.value.id }}"
  loop: "{{ pure1_volumes['pure1_volumes']['serial_numbers'] | dict2items }}"
"""

RETURN = r"""
pure1_volumes:
  description: Returns the volumes information collected from Pure1, keyed on volume serial number
  returned: always
  type: dict
  contains:
    serial_numbers:
      description: Dictionary of volumes keyed on volume serial number
      type: dict
      contains:
        id:
          description: The globally unique Pure1 ID (NAID) of the volume
          type: str
        name:
          description: The volume name
          type: str
        provisioned:
          description: Provisioned (virtual) size of the volume in bytes
          type: int
        serial:
          description: Serial number generated by Purity when the volume was created
          type: str
        array:
          description: The first array on which the volume exists (kept for backwards compatibility)
          type: dict
        arrays:
          description: All arrays on which the volume exists (e.g. both legs of a pod)
          type: list
          elements: dict
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.everpure.pure1.plugins.module_utils.pure1 import (
    get_pure1,
    pure1_argument_spec,
)
import time


def generate_volumes_dict(module, pure_1):
    volumes_info = {}
    if module.params["array"]:
        volumes = list(
            pure_1.get_volumes(
                filter="arrays.name='" + module.params["array"] + "'"
            ).items
        )
    else:
        volumes = list(pure_1.get_volumes().items)
    for volume in range(0, len(volumes)):
        serial = volumes[volume].serial
        created = time.strftime(
            "%Y-%m-%d %H:%M:%S UTC",
            time.gmtime(volumes[volume].created / 1000),
        )
        volumes_info[serial] = {
            "id": getattr(volumes[volume], "id", None),
            "name": volumes[volume].name,
            "created": created,
            "eradicated": volumes[volume].eradicated,
            "destroyed": volumes[volume].destroyed,
            "provisioned": volumes[volume].provisioned,
            "source": [],
            "serial": getattr(volumes[volume], "serial", None),
            "pod": [],
            "array": {
                "name": volumes[volume].arrays[0].name,
                "fqdn": volumes[volume].arrays[0].fqdn,
            },
            "arrays": [
                {"name": array.name, "fqdn": getattr(array, "fqdn", None)}
                for array in volumes[volume].arrays
            ],
        }
        if getattr(volumes[volume], "source", None):
            volumes_info[serial]["source"] = volumes[volume].source.name
        if getattr(volumes[volume], "pod", None):
            volumes_info[serial]["pod"] = volumes[volume].pod.name
    return volumes_info


def main():
    argument_spec = pure1_argument_spec()
    argument_spec.update(dict(array=dict(type="str")))
    module = AnsibleModule(argument_spec, supports_check_mode=True)
    pure_1 = get_pure1(module)

    volumes = {}

    volumes["serial_numbers"] = generate_volumes_dict(module, pure_1)

    module.exit_json(changed=False, pure1_volumes=volumes)


if __name__ == "__main__":
    main()
